/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simandi.ui.panels;

/**
 *
 * @author Tya
 */
public class Laporan extends javax.swing.JPanel implements simandi.service.BahasaService.bahasaChangeListener {

    /**
     * Creates new form
     */
    public Laporan() {
        initComponents();
        simandi.service.BahasaService.registerListener(this);
        onLanguageChanged();
        // =====================================================================
        // PERMAK TEKS & TABEL AGAR SUPER JELAS DAN MEWAH:
        // =====================================================================
        tblUser.setForeground(new java.awt.Color(44, 62, 80)); // Teks warna Hitam/Navy elegan (Sangat Jelas!)
        tblUser.setBackground(java.awt.Color.WHITE);           // Background baris putih bersih
        tblUser.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 13)); // Font lebih modern
        tblUser.setRowHeight(30);                              // Tinggi baris lebih lega (tidak sempit)

        // Bonus: Ubah warna Header (Judul Kolom Atas) jadi Biru Mewah teks Putih:
        tblUser.getTableHeader().setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
        tblUser.getTableHeader().setBackground(new java.awt.Color(52, 152, 219));
        tblUser.getTableHeader().setForeground(java.awt.Color.BLUE);
        loadDataLaporan();

        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent evt) {
                System.out.println("--> [AUTO-REFRESH] Tab Laporan dibuka! Memuat log terbaru...");
                loadDataLaporan();
            }
        });
    }

    /**
     * Method untuk membaca riwayat absensi dari MongoDB dan menaruhnya di tabel
     */
    public void loadDataLaporan() {

        Thread loaderThread = new Thread(() -> {

            System.out.println("--> [THREAD-LAPORAN] Mulai membaca data log absensi di background...");

            try {
                simandi.service.LogAbsensiService logService = new simandi.service.LogAbsensiService();
                java.util.List<simandi.objek.LogAbsensi> daftarLog = logService.ambilSemuaLog();
                simandi.service.AnggotaService2 anggotaService = new simandi.service.AnggotaService2();

                javax.swing.SwingUtilities.invokeLater(() -> {

                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblUser.getModel();
                    model.setRowCount(0); // Bersihkan baris tabel lama

                    for (simandi.objek.LogAbsensi log : daftarLog) {
                        // Cari data anggota lengkap untuk mendapatkan NIM terdekripsi, Kelas, dan Jurusan
                        simandi.objek.Anggota a = anggotaService.cariAnggotaByUid(log.getUidRfid());
                        String nimAsli = (a != null && a.getNim() != null) ? simandi.util.EncryptionUtils.decrypt(a.getNim()) : "-";
                        String kelas = (a != null) ? a.getKelas() : "-";
                        String jurusan = (a != null) ? a.getJurusan() : "-";
                        model.addRow(new Object[]{
                            log.getUidRfid(),
                            log.getNamaLengkap(),
                            nimAsli,
                            kelas,
                            simandi.service.BahasaService.get(jurusan),
                            log.getStatus(),
                            log.getLocalDateTimewaktuTap() // Tampilkan jam & tanggal di kolom Aksi
                        });
                    }
                    System.out.println("--> [THREAD-LAPORAN] Sukses memuat " + daftarLog.size() + " data ke tabel Laporan!");
                });
            } catch (Exception e) {
                e.printStackTrace();
                System.err.println("Gagal memuat data laporan: " + e.getMessage());
            }
        }, "Thread-Laporan-Loader");
        loaderThread.setDaemon(true);
        loaderThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradient1 = new smd.swing.gradient();
        btnLaporan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();

        gradient1.setPreferredSize(new java.awt.Dimension(790, 1553));

        btnLaporan.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
        });

        jPanel2.setLayout(new java.awt.BorderLayout());

        tblUser.setForeground(new java.awt.Color(255, 255, 255));
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "UID Kartu", "Nama Mahasiswa", "Nim", "Kelas", "Jurusan", "Status Anggota", "Waktu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout gradient1Layout = new javax.swing.GroupLayout(gradient1);
        gradient1.setLayout(gradient1Layout);
        gradient1Layout.setHorizontalGroup(
            gradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradient1Layout.createSequentialGroup()
                .addGap(713, 713, 713)
                .addComponent(btnLaporan)
                .addContainerGap(756, Short.MAX_VALUE))
            .addGroup(gradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gradient1Layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );
        gradient1Layout.setVerticalGroup(
            gradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradient1Layout.createSequentialGroup()
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 787, Short.MAX_VALUE))
            .addGroup(gradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gradient1Layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradient1, javax.swing.GroupLayout.DEFAULT_SIZE, 1553, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradient1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );

        gradient1.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        loadDataLaporan();
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked

    }//GEN-LAST:event_tblUserMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLaporan;
    private smd.swing.gradient gradient1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables

        @Override
    public void onLanguageChanged() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            // 1. Ubah Teks Judul Atas (Jika nama variabel label judulmu btnLaporan):
            if (btnLaporan != null) {
                btnLaporan.setText(simandi.service.BahasaService.get("ui.report.title"));
            }
            
            // 2. Ubah Nama 7 Kolom Tabel (UID, Nama, NIM, Kelas, Jurusan, Status, Waktu)
            if (tblUser != null && tblUser.getColumnModel().getColumnCount() >= 7) {
                tblUser.getColumnModel().getColumn(0).setHeaderValue(simandi.service.BahasaService.get("ui.report.col.uid"));
                tblUser.getColumnModel().getColumn(1).setHeaderValue(simandi.service.BahasaService.get("ui.report.col.name"));
                tblUser.getColumnModel().getColumn(2).setHeaderValue(simandi.service.BahasaService.get("ui.report.col.nim"));
                tblUser.getColumnModel().getColumn(3).setHeaderValue(simandi.service.BahasaService.get("ui.report.col.class"));
                tblUser.getColumnModel().getColumn(4).setHeaderValue(simandi.service.BahasaService.get("ui.report.col.major"));
                tblUser.getColumnModel().getColumn(5).setHeaderValue(simandi.service.BahasaService.get("ui.report.col.status"));
                tblUser.getColumnModel().getColumn(6).setHeaderValue(simandi.service.BahasaService.get("ui.report.col.time"));
                
                tblUser.getTableHeader().repaint(); // Refresh tampilan header tabel
            }
            
            // 3. Muat ulang isi tabel agar teks jurusan/status ikut berubah bahasa!
            loadDataLaporan();
            
            this.revalidate();
            this.repaint();
        });
    }


}
