/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simandi.ui.panels;



import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.Locale;
import java.util.prefs.Preferences;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import simandi.service.BahasaService;
import smd.swing.SlidingLanguageToggle;
/**
 *
 * @author Adies
 */
public class Setting extends javax.swing.JPanel implements simandi.service.BahasaService.bahasaChangeListener {
    
    public static String statusLang;
    public static Preferences prefs = Preferences.userNodeForPackage(Setting.class);
     private SlidingLanguageToggle languageToggle;
    /**
     * Creates new form Setting
     */
    public Setting() {
        BahasaService.setLocale(Locale.forLanguageTag(Setting.prefs.get("LANGUAGE", "id"))); 
        initComponents();
        initCustomToggle();
        simandi.service.BahasaService.registerListener(this);
    }
    private void initCustomToggle() {
        // 1. Atur layout agar tombol berada tepat di tengah kotak border
        jPanel4.setLayout(new FlowLayout(FlowLayout.CENTER, 15, 25));
        
        // 2. Panggil SlidingLanguageToggle 3 bahasa (Indonesia, Inggris, Malaysia)
        languageToggle = new SlidingLanguageToggle();
        
        // 3. Beri ukuran luas (300x45) agar ketiga teks tidak terpotong
        languageToggle.setPreferredSize(new Dimension(300, 45));
        
        // 4. Set posisi awal sesuai yang tersimpan di preferensi
        String currentLang = prefs.get("LANGUAGE", "id");
        languageToggle.setSelectedLanguageIndexByString(currentLang);
        
        // 5. Hubungkan saat tombol digeser agar ganti bahasa secara Global!
        languageToggle.addActionListener(e -> {
            String selectedLang = languageToggle.getSelectedLanguageString();
            prefs.put("LANGUAGE", selectedLang);
            BahasaService.setLocale(Locale.forLanguageTag(selectedLang));
        });
        
        // 6. Bersihkan kotak dan masukkan tombol barumu
        jPanel4.removeAll();
        jPanel4.add(languageToggle);
        jPanel4.revalidate();
        jPanel4.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), BahasaService.get("ui.setting.lang"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
    @Override
    public void onLanguageChanged() {
        SwingUtilities.invokeLater(() -> {
            this.revalidate();
            this.repaint();
            
            // Update border title
            jPanel4.setBorder(BorderFactory.createTitledBorder(
                new LineBorder(new Color(0, 0, 0), 1, true), 
                BahasaService.get("ui.setting.lang"), // Pastikan ini BahasaService bukan I18nService
                TitledBorder.CENTER, 
                TitledBorder.DEFAULT_POSITION, 
                new Font("Segoe UI", 1, 14))
            );
        });
    }




        // =========================================================================
    // KODE TES PREVIEW DENGAN DETEKTOR ERROR OTOMATIS
    // =========================================================================
    public static void main(String args[]) {
        /* Set Look and Feel Nimbus */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(() -> {
            try {
                javax.swing.JFrame testFrame = new javax.swing.JFrame("Preview Halaman Setting (3 Bahasa)");
                testFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                testFrame.getContentPane().add(new Setting());
                testFrame.setSize(700, 450);
                testFrame.setLocationRelativeTo(null);
                testFrame.setVisible(true);
            } catch (Throwable e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(null, 
                    "Gagal memuat halaman Setting!\nPenyebab: " + e.toString(), 
                    "Terjadi Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        });
    }
}
