/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simandi.ui.dialogs;

/**
 *
 * @author Lenovo
 */
public class EditDataAnggota extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditDataAnggota.class.getName());

    /**
     * Creates new form EditDataAnggota
     */
    public EditDataAnggota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UIDKartu = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        NIM = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        Jurusan = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        jTextField1UIDKartu = new javax.swing.JTextField();
        jTextField2Nama = new javax.swing.JTextField();
        jTextField3NIM = new javax.swing.JTextField();
        jTextField4Kelas = new javax.swing.JTextField();
        jTextField5Jurusan = new javax.swing.JTextField();
        jTextField6Status = new javax.swing.JTextField();
        jButton1Simpan = new javax.swing.JButton();
        jButton2Batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(762, 569));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Edit Data Anggota Mahasiswa ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 80));

        UIDKartu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        UIDKartu.setForeground(new java.awt.Color(0, 0, 0));
        UIDKartu.setText("UID Kartu");
        jPanel1.add(UIDKartu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        Nama.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Nama.setForeground(new java.awt.Color(0, 0, 0));
        Nama.setText("Nama");
        jPanel1.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        NIM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        NIM.setForeground(new java.awt.Color(0, 0, 0));
        NIM.setText("NIM");
        jPanel1.add(NIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        Kelas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Kelas.setForeground(new java.awt.Color(0, 0, 0));
        Kelas.setText("Kelas");
        jPanel1.add(Kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        Jurusan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Jurusan.setForeground(new java.awt.Color(0, 0, 0));
        Jurusan.setText("Jurusan");
        jPanel1.add(Jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        Status.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Status.setForeground(new java.awt.Color(0, 0, 0));
        Status.setText("Status");
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jTextField1UIDKartu.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1UIDKartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1UIDKartuActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1UIDKartu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 142, 350, 30));

        jTextField2Nama.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField2Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 192, 350, 30));

        jTextField3NIM.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField3NIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 242, 350, 30));

        jTextField4Kelas.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField4Kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 292, 350, 30));

        jTextField5Jurusan.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField5Jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 342, 350, 30));

        jTextField6Status.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField6Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 350, 30));

        jButton1Simpan.setBackground(new java.awt.Color(0, 255, 204));
        jButton1Simpan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1Simpan.setForeground(new java.awt.Color(0, 0, 0));
        jButton1Simpan.setText("Simpan");
        jButton1Simpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        jPanel1.add(jButton1Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 180, 40));

        jButton2Batal.setBackground(new java.awt.Color(204, 0, 0));
        jButton2Batal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton2Batal.setForeground(new java.awt.Color(255, 255, 255));
        jButton2Batal.setText("Batal");
        jButton2Batal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        jPanel1.add(jButton2Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 190, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 762, 596));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1UIDKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1UIDKartuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1UIDKartuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditDataAnggota().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jurusan;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel NIM;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel UIDKartu;
    private javax.swing.JButton jButton1Simpan;
    private javax.swing.JButton jButton2Batal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1UIDKartu;
    private javax.swing.JTextField jTextField2Nama;
    private javax.swing.JTextField jTextField3NIM;
    private javax.swing.JTextField jTextField4Kelas;
    private javax.swing.JTextField jTextField5Jurusan;
    private javax.swing.JTextField jTextField6Status;
    // End of variables declaration//GEN-END:variables
}
